import type { Dialogue } from "../types";

/**
 * Conversas do app. Princípios de design:
 * - cada personagem tem VOZ própria (Yuki caótica, a paquera fofa-tímida,
 *   Kenji profissional-gentil, Hana acolhedora, Aiko professora) e vários
 *   diálogos, para nunca repetir a mesma conversa;
 * - toda fala existe nos dois registros (toggle polido⇄casual) e traz kana
 *   sem kanji para iniciantes (politeKana/casualKana);
 * - os finais são ABERTOS — um convite, uma provocação, um "até amanhã" que
 *   dá vontade de voltar — nunca um corte seco;
 * - `week` marca o nível: os chats acompanham o vocabulário já aprendido.
 */
export const DIALOGUES: Dialogue[] = [
  // ─────────────────────────── YUKI (casual, elétrica) ───────────────────────────
  {
    id: "w1-yuki-intro",
    week: 1,
    medium: "irl",
    title: { pt: "Conhecendo a Yuki", en: "Meeting Yuki" },
    scene: {
      pt: "Evento de intercâmbio de idiomas. Uma garota de maria-chiquinha roxa senta na sua frente com um sorrisão.",
      en: "Language exchange event. A girl with purple twintails plops down across from you, grinning.",
    },
    register: "casual",
    characterId: "yuki",
    lines: [
      {
        speaker: "yuki",
        polite: "こんにちは！はじめまして。ゆきです。",
        casual: "こんにちは！はじめまして、ゆきだよ〜",
        translation: { pt: "Oi! Prazer, sou a Yuki.", en: "Hi! Nice to meet you, I'm Yuki." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "はじめまして。よろしくお願いします。",
            politeKana: "はじめまして。よろしくおねがいします。",
            casual: "はじめまして！よろしくね。",
            translation: { pt: "Prazer! Conto com você.", en: "Nice to meet you! Looking forward to it." },
          },
          {
            polite: "こんにちは。お元気ですか。",
            politeKana: "こんにちは。おげんきですか。",
            casual: "こんにちは！元気？",
            casualKana: "こんにちは！げんき？",
            translation: { pt: "Olá! Tudo bem?", en: "Hello! How are you?" },
          },
        ],
      },
      {
        speaker: "yuki",
        polite: "元気です！日本語、上手ですね。どこで勉強しているんですか？",
        politeKana: "げんきです！にほんご、じょうずですね。どこでべんきょうしているんですか？",
        casual: "元気元気！日本語うまいじゃん。どこで勉強してるの？",
        casualKana: "げんきげんき！にほんごうまいじゃん。どこでべんきょうしてるの？",
        translation: { pt: "Tô ótima! Seu japonês é bom, hein. Onde você estuda?", en: "Great! Your Japanese is good, huh. Where do you study?" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "アプリで勉強しています。",
            politeKana: "アプリでべんきょうしています。",
            casual: "アプリで勉強してる〜",
            casualKana: "アプリでべんきょうしてる〜",
            translation: { pt: "Estudo por um app.", en: "I study with an app." },
          },
          {
            polite: "まだ初心者です…",
            politeKana: "まだしょしんしゃです…",
            casual: "まだ初心者だよ〜",
            casualKana: "まだしょしんしゃだよ〜",
            translation: { pt: "Ainda sou iniciante…", en: "I'm still a beginner…" },
          },
        ],
      },
      {
        speaker: "yuki",
        polite: "いいですね！じゃあ、私が先生になります。毎週会いましょう！",
        politeKana: "いいですね！じゃあ、わたしがせんせいになります。まいしゅうあいましょう！",
        casual: "いいじゃん！じゃあ私が先生ね。毎週会お〜ぜったい！",
        casualKana: "いいじゃん！じゃあわたしがせんせいね。まいしゅうあお〜ぜったい！",
        translation: { pt: "Que legal! Então eu vou ser sua professora. Vamos nos ver toda semana — juro!", en: "Nice! Then I'll be your teacher. Let's meet every week — I mean it!" },
      },
    ],
  },
  {
    id: "w2-yuki-karaoke",
    week: 2,
    medium: "text",
    title: { pt: "Yuki te chama pro karaokê 🎤", en: "Yuki drags you to karaoke 🎤" },
    scene: {
      pt: "Sexta à noite. Seu celular vibra sem parar — é a Yuki, com energia de sobra.",
      en: "Friday night. Your phone buzzes nonstop — it's Yuki, running on pure energy.",
    },
    register: "casual",
    characterId: "yuki",
    lines: [
      {
        speaker: "yuki",
        polite: "今、ひまですか？ひまですよね？",
        politeKana: "いま、ひまですか？ひまですよね？",
        casual: "ねえねえ、今ひま？ひまだよね？？",
        casualKana: "ねえねえ、いまひま？ひまだよね？？",
        translation: { pt: "Ei, tá livre agora? Tá livre, né?? 😆", en: "Hey hey, you free right now? You're free, right?? 😆" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "はい、ひまです。どうしたんですか？",
            politeKana: "はい、ひまです。どうしたんですか？",
            casual: "うん、ひまだよ。どうしたの？",
            casualKana: "うん、ひまだよ。どうしたの？",
            translation: { pt: "Sim, tô livre. O que foi?", en: "Yeah, I'm free. What's up?" },
          },
          {
            polite: "ちょっとつかれています…",
            politeKana: "ちょっとつかれています…",
            casual: "ちょっとつかれてる〜",
            casualKana: "ちょっとつかれてる〜",
            translation: { pt: "Tô meio cansado(a)…", en: "I'm kinda tired…" },
          },
        ],
      },
      {
        speaker: "yuki",
        polite: "カラオケに行きましょう！歌えば元気になりますよ！",
        politeKana: "カラオケにいきましょう！うたえばげんきになりますよ！",
        casual: "カラオケ行こ！歌えば元気になるって〜",
        casualKana: "カラオケいこ！うたえばげんきになるって〜",
        translation: { pt: "Vamos pro karaokê! Cantar recarrega, confia!", en: "Let's hit karaoke! Singing fixes everything, trust me!" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "いいですね！行きましょう。",
            politeKana: "いいですね！いきましょう。",
            casual: "いいね！行く行く！",
            casualKana: "いいね！いくいく！",
            translation: { pt: "Boa! Bora!", en: "Nice! I'm in, let's go!" },
          },
          {
            polite: "でも、私は歌が下手です…",
            politeKana: "でも、わたしはうたがへたです…",
            casual: "でも歌へたなんだよね〜",
            casualKana: "でも、うたへたなんだよね〜",
            translation: { pt: "Mas eu canto mal…", en: "But I'm a bad singer…" },
          },
        ],
      },
      {
        speaker: "yuki",
        polite: "大丈夫です！下手でも楽しいですから。じゃあ、駅で待っていますね！",
        politeKana: "だいじょうぶです！へたでもたのしいですから。じゃあ、えきでまっていますね！",
        casual: "へたでもいいの！楽しいんだから〜じゃあ駅で待ってるね、ぜったい来てよ！",
        casualKana: "へたでもいいの！たのしいんだから〜じゃあえきでまってるね、ぜったいきてよ！",
        translation: { pt: "Cantar mal não importa, o barato é a diversão! Te espero na estação — não me dá bolo, hein! 🎶", en: "Being bad is fine, it's about fun! I'll wait at the station — you'd better show up! 🎶" },
      },
    ],
  },
  {
    id: "w2-yuki-teasing",
    week: 2,
    medium: "irl",
    title: { pt: "Yuki tira sarro (com carinho)", en: "Yuki teases you (lovingly)" },
    scene: {
      pt: "No café depois da aula. Você solta uma frase e a Yuki cai na gargalhada — mas do jeito bom.",
      en: "At a café after class. You say a line and Yuki bursts out laughing — the good kind.",
    },
    register: "casual",
    characterId: "yuki",
    lines: [
      {
        speaker: "yuki",
        polite: "今の発音、かわいかったですよ！もう一回言ってください。",
        politeKana: "いまのはつおん、かわいかったですよ！もういちどいってください。",
        casual: "今の発音、かわいい〜！もう一回言って？笑",
        casualKana: "いまのはつおん、かわいい〜！もういっかいいって？わら",
        translation: { pt: "Sua pronúncia agora foi fofa! Fala de novo? kkk", en: "Your pronunciation just now was cute! Say it again? lol" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "えっ、へんでしたか？",
            politeKana: "えっ、へんでしたか？",
            casual: "えっ、へんだった？",
            casualKana: "えっ、へんだった？",
            translation: { pt: "Ué, ficou estranho?", en: "Huh, was it weird?" },
          },
          {
            polite: "からかわないでください〜",
            politeKana: "からかわないでください〜",
            casual: "からかわないでよ〜",
            casualKana: "からかわないでよ〜",
            translation: { pt: "Para de tirar sarro~", en: "Quit teasing me~" },
          },
        ],
      },
      {
        speaker: "yuki",
        polite: "ごめんごめん！でも、本当に上手になっていますよ。",
        politeKana: "ごめんごめん！でも、ほんとうにじょうずになっていますよ。",
        casual: "ごめんごめん！でもマジで上手くなってるよ？",
        casualKana: "ごめんごめん！でもマジでうまくなってるよ？",
        translation: { pt: "Foi mal, foi mal! Mas sério, você tá ficando bom mesmo.", en: "Sorry, sorry! But seriously, you're actually getting good." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "本当ですか？うれしいです。",
            politeKana: "ほんとうですか？うれしいです。",
            casual: "ほんと？うれしい〜",
            casualKana: "ほんと？うれしい〜",
            translation: { pt: "Sério? Que bom!", en: "Really? That makes me happy!" },
          },
          {
            polite: "ゆきさんのおかげです。",
            politeKana: "ゆきさんのおかげです。",
            casual: "ゆきのおかげだよ！",
            casualKana: "ゆきのおかげだよ！",
            translation: { pt: "É graças a você, Yuki.", en: "It's thanks to you, Yuki." },
          },
        ],
      },
      {
        speaker: "yuki",
        polite: "ふふ、まかせてください。次はもっと難しい言葉を教えますね！",
        politeKana: "ふふ、まかせてください。つぎはもっとむずかしいことばをおしえますね！",
        casual: "ふふ、まかせて！次はもっと難しいの教えちゃう〜楽しみにしててね！",
        casualKana: "ふふ、まかせて！つぎはもっとむずかしいのおしえちゃう〜たのしみにしててね！",
        translation: { pt: "Hehe, pode deixar comigo. Da próxima te ensino palavras mais difíceis — pode esperar! 😉", en: "Hehe, leave it to me. Next time I'll teach you harder words — look forward to it! 😉" },
      },
    ],
  },

  // ─────────────────── PAQUERA (Haruto/Mei — fofo, tímido, atento) ───────────────────
  {
    id: "w1-crush-cafe",
    week: 1,
    medium: "irl",
    title: { pt: "Paquera no café ☕", en: "Café crush ☕" },
    scene: {
      pt: "O café perto da estação. Sua paquera já decorou seu pedido — e hoje puxou papo.",
      en: "The café by the station. Your crush memorized your order — and today they're chatting you up.",
    },
    register: "casual",
    characterId: "crush",
    lines: [
      {
        speaker: "crush",
        polite: "こんにちは。いつものコーヒーですか？",
        casual: "こんにちは〜。いつものコーヒー？",
        translation: { pt: "Oi! O café de sempre?", en: "Hi! The usual coffee?" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "はい、お願いします！",
            politeKana: "はい、おねがいします！",
            casual: "うん、お願い！",
            casualKana: "うん、おねがい！",
            translation: { pt: "Sim, por favor!", en: "Yes, please!" },
          },
          {
            polite: "覚えてくれたんですか？うれしいです。",
            politeKana: "おぼえてくれたんですか？うれしいです。",
            casual: "覚えててくれたんだ、うれしい〜",
            casualKana: "おぼえててくれたんだ、うれしい〜",
            translation: { pt: "Você lembrou? Que fofo!", en: "You remembered? That's sweet!" },
          },
        ],
      },
      {
        speaker: "crush",
        polite: "もちろんです。あなたのことは、よく覚えていますよ。",
        politeKana: "もちろんです。あなたのことは、よくおぼえていますよ。",
        casual: "もちろん。君のことはよく覚えてるよ。",
        casualKana: "もちろん。きみのことはよくおぼえてるよ。",
        translation: { pt: "Claro. De você eu lembro bem. 😊", en: "Of course. I remember you well. 😊" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "ありがとうございます…！",
            casual: "ありがとう…！",
            translation: { pt: "Obrigado(a)…!", en: "Thank you…!" },
          },
          {
            polite: "ちょっと、はずかしいです。",
            politeKana: "ちょっと、はずかしいです。",
            casual: "ちょっと、はずかしいな〜",
            casualKana: "ちょっと、はずかしいな〜",
            translation: { pt: "Ai, que vergonha~", en: "Aw, now I'm embarrassed~" },
          },
        ],
      },
      {
        speaker: "crush",
        polite: "コーヒー、どうぞ。カップに何か書いておきました。またどうぞ。",
        politeKana: "コーヒー、どうぞ。カップになにかかいておきました。またどうぞ。",
        casual: "はい、コーヒー。カップに何か書いといたよ。…また来てね。",
        casualKana: "はい、コーヒー。カップになにかかいといたよ。…またきてね。",
        translation: { pt: "Aqui seu café. Escrevi algo no copo… Volta, tá? ☕💬", en: "Here's your coffee. I wrote something on the cup… Come back, okay? ☕💬" },
      },
    ],
  },
  {
    id: "w2-crush-goodnight",
    week: 2,
    medium: "text",
    title: { pt: "A paquera te manda mensagem 🌙", en: "Your crush texts you first 🌙" },
    scene: {
      pt: "Quase meia-noite. O celular acende: uma mensagem de um número que você salvou faz pouco tempo.",
      en: "Almost midnight. Your phone lights up: a message from a number you saved not long ago.",
    },
    register: "casual",
    characterId: "crush",
    lines: [
      {
        speaker: "crush",
        polite: "おつかれさまです。今日も来てくれて、ありがとうございました。",
        politeKana: "おつかれさまです。きょうもきてくれて、ありがとうございました。",
        casual: "おつかれ〜。今日も来てくれてありがとね😊",
        casualKana: "おつかれ〜。きょうもきてくれてありがとね",
        translation: { pt: "Boa noite! Obrigado(a) por aparecer de novo hoje 😊", en: "Hey, good work today. Thanks for coming by again 😊" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "こちらこそ、ありがとうございます。",
            politeKana: "こちらこそ、ありがとうございます。",
            casual: "こちらこそ〜！",
            casualKana: "こちらこそ〜！",
            translation: { pt: "Eu que agradeço!", en: "Likewise — thank you!" },
          },
          {
            polite: "メッセージ、うれしいです。",
            politeKana: "メッセージ、うれしいです。",
            casual: "メッセージうれしい〜",
            casualKana: "メッセージうれしい〜",
            translation: { pt: "Fiquei feliz com a mensagem.", en: "Your message made me happy." },
          },
        ],
      },
      {
        speaker: "crush",
        polite: "あの…明日も来ますか？…なんて、聞いてみました。",
        politeKana: "あの…あしたもきますか？…なんて、きいてみました。",
        casual: "あのさ…明日も来る？…なんてね😳",
        casualKana: "あのさ…あしたもくる？…なんてね",
        translation: { pt: "Ei… você vem amanhã também? …brincadeira 😳", en: "Hey… are you coming tomorrow too? …just kidding 😳" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "もちろん、行きます！",
            politeKana: "もちろん、いきます！",
            casual: "もちろん行くよ！",
            casualKana: "もちろんいくよ！",
            translation: { pt: "Claro que vou!", en: "Of course I'll be there!" },
          },
          {
            polite: "会いたいので、行きますね。",
            politeKana: "あいたいので、いきますね。",
            casual: "会いたいから行っちゃう〜",
            casualKana: "あいたいからいっちゃう〜",
            translation: { pt: "Quero te ver, então vou sim.", en: "I want to see you, so I'll come." },
          },
        ],
      },
      {
        speaker: "crush",
        polite: "よかった。じゃあ、待っていますね。おやすみなさい。",
        politeKana: "よかった。じゃあ、まっていますね。おやすみなさい。",
        casual: "よかった。じゃあ待ってる。おやすみ〜また明日ね🌙",
        casualKana: "よかった。じゃあまってる。おやすみ〜またあしたね",
        translation: { pt: "Que bom. Então te espero. Boa noite~ até amanhã 🌙", en: "Good. I'll be waiting, then. Goodnight~ see you tomorrow 🌙" },
      },
    ],
  },

  // ─────────────────────── KENJI (polido, profissional, gentil) ───────────────────────
  {
    id: "w1-kenji-morning",
    week: 1,
    medium: "irl",
    title: { pt: "Manhã no escritório", en: "Morning at the office" },
    scene: {
      pt: "Seu primeiro dia de estágio em Tóquio. Kenji, seu colega, chega na sua mesa com dois cafés.",
      en: "Your first day interning in Tokyo. Kenji, your coworker, comes to your desk with two coffees.",
    },
    register: "polite",
    characterId: "kenji",
    lines: [
      {
        speaker: "kenji",
        polite: "おはようございます。けんじです。よろしくお願いします。",
        politeKana: "おはようございます。けんじです。よろしくおねがいします。",
        casual: "おはよう。けんじだよ。よろしく。",
        translation: { pt: "Bom dia. Sou o Kenji. Prazer, conto com você.", en: "Good morning. I'm Kenji. Nice to work with you." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "おはようございます！よろしくお願いします。",
            politeKana: "おはようございます！よろしくおねがいします。",
            casual: "おはよう！よろしくね。",
            translation: { pt: "Bom dia! Prazer, conto com você.", en: "Good morning! Nice to work with you too." },
          },
          {
            polite: "はじめまして。すみません、日本語はまだまだです…",
            politeKana: "はじめまして。すみません、にほんごはまだまだです…",
            casual: "はじめまして。ごめん、日本語まだまだ…",
            casualKana: "はじめまして。ごめん、にほんごまだまだ…",
            translation: { pt: "Prazer. Desculpa, meu japonês ainda é fraco…", en: "Nice to meet you. Sorry, my Japanese is still shaky…" },
          },
        ],
      },
      {
        speaker: "kenji",
        polite: "大丈夫ですよ。これ、コーヒーです。よかったらどうぞ。",
        politeKana: "だいじょうぶですよ。これ、コーヒーです。よかったらどうぞ。",
        casual: "大丈夫だよ。これ、コーヒー。よかったらどうぞ。",
        casualKana: "だいじょうぶだよ。これ、コーヒー。よかったらどうぞ。",
        translation: { pt: "Fica tranquilo. Toma, um café. Se quiser, é seu.", en: "No worries. Here, a coffee. Have it if you'd like." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "わあ、ありがとうございます！",
            casual: "わあ、ありがとう！",
            translation: { pt: "Nossa, obrigado(a)!", en: "Oh wow, thank you!" },
          },
          {
            polite: "やさしいですね。助かります。",
            politeKana: "やさしいですね。たすかります。",
            casual: "やさしいね。助かる〜",
            casualKana: "やさしいね。たすかる〜",
            translation: { pt: "Que gentil. Você me salvou.", en: "That's kind of you. You're a lifesaver." },
          },
        ],
      },
      {
        speaker: "kenji",
        polite: "困ったときは、いつでも聞いてください。あとで、社内を案内しますね。",
        politeKana: "こまったときは、いつでもきいてください。あとで、しゃないをあんないしますね。",
        casual: "困ったら、いつでも聞いて。あとで社内を案内するよ。",
        casualKana: "こまったら、いつでもきいて。あとでしゃないをあんないするよ。",
        translation: { pt: "Se precisar de algo, pode me chamar. Depois te mostro o escritório.", en: "Whenever you're stuck, just ask. I'll show you around the office later." },
      },
    ],
  },
  {
    id: "w2-kenji-lunch",
    week: 2,
    medium: "irl",
    title: { pt: "Kenji te convida pro almoço", en: "Kenji invites you to lunch" },
    scene: {
      pt: "Meio-dia. O time começa a se levantar e o Kenji vira pra você, educado como sempre.",
      en: "Noon. The team starts getting up, and Kenji turns to you, courteous as ever.",
    },
    register: "polite",
    characterId: "kenji",
    lines: [
      {
        speaker: "kenji",
        polite: "お昼ですね。みんなでご飯に行きますが、一緒にどうですか？",
        politeKana: "おひるですね。みんなでごはんにいきますが、いっしょにどうですか？",
        casual: "お昼だね。みんなでご飯行くけど、一緒にどう？",
        casualKana: "おひるだね。みんなでごはんいくけど、いっしょにどう？",
        translation: { pt: "Hora do almoço. A galera vai comer — vem junto?", en: "Lunchtime. We're all going to eat — want to join?" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "はい、ぜひ行きたいです！",
            politeKana: "はい、ぜひいきたいです！",
            casual: "うん、ぜひ行きたい！",
            casualKana: "うん、ぜひいきたい！",
            translation: { pt: "Sim, quero muito ir!", en: "Yes, I'd love to!" },
          },
          {
            polite: "いいんですか？おじゃまじゃないですか？",
            politeKana: "いいんですか？おじゃまじゃないですか？",
            casual: "いいの？じゃまじゃない？",
            casualKana: "いいの？じゃまじゃない？",
            translation: { pt: "Posso mesmo? Não vou atrapalhar?", en: "Is that okay? I won't be in the way?" },
          },
        ],
      },
      {
        speaker: "kenji",
        polite: "もちろんです。近くにおいしいラーメン屋がありますよ。",
        politeKana: "もちろんです。ちかくにおいしいラーメンやがありますよ。",
        casual: "もちろん。近くにうまいラーメン屋があるんだ。",
        casualKana: "もちろん。ちかくにうまいラーメンやがあるんだ。",
        translation: { pt: "Claro que pode. Tem uma casa de ramen ótima aqui perto.", en: "Of course. There's a great ramen place nearby." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "ラーメン、大好きです！",
            politeKana: "ラーメン、だいすきです！",
            casual: "ラーメン大好き！",
            casualKana: "ラーメンだいすき！",
            translation: { pt: "Amo ramen!", en: "I love ramen!" },
          },
          {
            polite: "おすすめは何ですか？",
            politeKana: "おすすめはなんですか？",
            casual: "おすすめは何？",
            casualKana: "おすすめはなに？",
            translation: { pt: "Qual você recomenda?", en: "What do you recommend?" },
          },
        ],
      },
      {
        speaker: "kenji",
        polite: "着いてから、ゆっくり選びましょう。では、こちらへどうぞ。",
        politeKana: "ついてから、ゆっくりえらびましょう。では、こちらへどうぞ。",
        casual: "着いてからゆっくり選ぼう。じゃあ、こっちだよ。",
        casualKana: "ついてからゆっくりえらぼう。じゃあ、こっちだよ。",
        translation: { pt: "Escolhe com calma quando a gente chegar. Vem, é por aqui.", en: "Let's pick once we get there. This way, please." },
      },
    ],
  },

  // ──────────────────────── HANA (vizinha, acolhedora, pausada) ────────────────────────
  {
    id: "w1-hana-tangerines",
    week: 1,
    medium: "irl",
    title: { pt: "A Hana te dá tangerinas 🍊", en: "Hana gives you tangerines 🍊" },
    scene: {
      pt: "No corredor do prédio. A vovó Hana, sua vizinha, aparece com uma sacola de mikan.",
      en: "In the building hallway. Granny Hana, your neighbor, appears with a bag of mikan.",
    },
    register: "polite",
    characterId: "hana",
    lines: [
      {
        speaker: "hana",
        polite: "あら、こんにちは。はい、みかん、どうぞ。たくさんありますからね。",
        politeKana: "あら、こんにちは。はい、みかん、どうぞ。たくさんありますからね。",
        casual: "あら、こんにちは。はい、みかんどうぞ。たくさんあるからね。",
        translation: { pt: "Ah, olá! Toma, umas tangerinas. Tenho um monte, viu.", en: "Oh, hello! Here, some tangerines. I've got plenty, dear." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "わあ、ありがとうございます！",
            casual: "わあ、ありがとう！",
            translation: { pt: "Nossa, muito obrigado(a)!", en: "Oh wow, thank you so much!" },
          },
          {
            polite: "いいんですか？うれしいです。",
            politeKana: "いいんですか？うれしいです。",
            casual: "いいの？うれしい〜",
            casualKana: "いいの？うれしい〜",
            translation: { pt: "Pode mesmo? Que alegria!", en: "Are you sure? That's so nice!" },
          },
        ],
      },
      {
        speaker: "hana",
        polite: "お元気でしたか？ちゃんと食べていますか？",
        politeKana: "おげんきでしたか？ちゃんとたべていますか？",
        casual: "元気だった？ちゃんと食べてる？",
        casualKana: "げんきだった？ちゃんとたべてる？",
        translation: { pt: "Tem passado bem? Anda comendo direitinho?", en: "Have you been well? Are you eating properly?" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "はい、元気です。ありがとうございます。",
            politeKana: "はい、げんきです。ありがとうございます。",
            casual: "うん、元気だよ。ありがとう。",
            casualKana: "うん、げんきだよ。ありがとう。",
            translation: { pt: "Sim, tô bem. Obrigado(a).", en: "Yes, I'm well. Thank you." },
          },
          {
            polite: "最近、少し忙しいです…",
            politeKana: "さいきん、すこしいそがしいです…",
            casual: "最近ちょっと忙しくて…",
            casualKana: "さいきんちょっといそがしくて…",
            translation: { pt: "Ando meio corrido ultimamente…", en: "I've been a little busy lately…" },
          },
        ],
      },
      {
        speaker: "hana",
        polite: "そうですか。無理はしないでくださいね。今度、お茶でも飲みに来てください。",
        politeKana: "そうですか。むりはしないでくださいね。こんど、おちゃでものみにきてください。",
        casual: "そう。無理しないでね。今度、お茶でも飲みにおいで。",
        casualKana: "そう。むりしないでね。こんど、おちゃでものみにおいで。",
        translation: { pt: "Entendo. Não se esforce demais, tá? Qualquer dia, vem tomar um chá comigo. 🍵", en: "I see. Don't push yourself too hard, okay? Come over for tea sometime. 🍵" },
      },
    ],
  },
  {
    id: "w2-hana-tea",
    week: 2,
    medium: "irl",
    title: { pt: "Chá com a Hana 🍵", en: "Tea with Hana 🍵" },
    scene: {
      pt: "Você aceitou o convite. A sala da Hana cheira a chá verde e há fotos antigas na parede.",
      en: "You took her up on it. Hana's living room smells of green tea, old photos on the wall.",
    },
    register: "polite",
    characterId: "hana",
    lines: [
      {
        speaker: "hana",
        polite: "よく来てくれましたね。さあ、座ってください。お茶をどうぞ。",
        politeKana: "よくきてくれましたね。さあ、すわってください。おちゃをどうぞ。",
        casual: "よく来てくれたね。さあ、座って。お茶どうぞ。",
        casualKana: "よくきてくれたね。さあ、すわって。おちゃどうぞ。",
        translation: { pt: "Que bom que veio! Vem, senta. Toma um chá.", en: "So glad you came! Come, sit. Have some tea." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "おじゃまします。いい香りですね。",
            politeKana: "おじゃまします。いいかおりですね。",
            casual: "おじゃま〜。いい香りだね。",
            casualKana: "おじゃま〜。いいかおりだね。",
            translation: { pt: "Com licença. Que cheirinho bom!", en: "Thanks for having me. It smells lovely." },
          },
          {
            polite: "この写真、どなたですか？",
            politeKana: "このしゃしん、どなたですか？",
            casual: "この写真、だれ？",
            casualKana: "このしゃしん、だれ？",
            translation: { pt: "Quem é nessa foto?", en: "Who's in this photo?" },
          },
        ],
      },
      {
        speaker: "hana",
        polite: "昔の家族の写真ですよ。みんな、遠くにいるんです。",
        politeKana: "むかしのかぞくのしゃしんですよ。みんな、とおくにいるんです。",
        casual: "昔の家族の写真よ。みんな、遠くにいるの。",
        casualKana: "むかしのかぞくのしゃしんよ。みんな、とおくにいるの。",
        translation: { pt: "É uma foto antiga da família. Estão todos longe agora.", en: "It's an old family photo. They're all far away now." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "そうなんですね。さびしくないですか？",
            politeKana: "そうなんですね。さびしくないですか？",
            casual: "そうなんだ。さびしくない？",
            casualKana: "そうなんだ。さびしくない？",
            translation: { pt: "Ah, entendo. Não fica com saudade?", en: "I see. Don't you get lonely?" },
          },
          {
            polite: "すてきなご家族ですね。",
            politeKana: "すてきなごかぞくですね。",
            casual: "すてきな家族だね。",
            casualKana: "すてきなかぞくだね。",
            translation: { pt: "Que família linda.", en: "What a lovely family." },
          },
        ],
      },
      {
        speaker: "hana",
        polite: "でも、あなたが来てくれて、うれしいです。また、いつでも来てくださいね。",
        politeKana: "でも、あなたがきてくれて、うれしいです。また、いつでもきてくださいね。",
        casual: "でも、あなたが来てくれてうれしいの。また、いつでもおいでね。",
        casualKana: "でも、あなたがきてくれてうれしいの。また、いつでもおいでね。",
        translation: { pt: "Mas fico feliz que você veio. Volta quando quiser, sempre. 🍊", en: "But I'm happy you came. Come by anytime, always. 🍊" },
      },
    ],
  },

  // ──────────────────────── AIKO (professora, meta, encorajadora) ────────────────────────
  {
    id: "w1-aiko-first",
    week: 1,
    medium: "irl",
    title: { pt: "Primeira aula com a Aiko 📖", en: "First class with Aiko 📖" },
    scene: {
      pt: "A sala de aula, tranquila. Aiko, sua professora, te recebe com um sorriso paciente.",
      en: "A calm classroom. Aiko, your teacher, greets you with a patient smile.",
    },
    register: "neutral",
    characterId: "aiko",
    lines: [
      {
        speaker: "aiko",
        polite: "こんにちは。あいこです。今日から一緒に勉強しましょうね。",
        politeKana: "こんにちは。あいこです。きょうからいっしょにべんきょうしましょうね。",
        casual: "こんにちは。あいこだよ。今日から一緒に勉強しよう。",
        casualKana: "こんにちは。あいこだよ。きょうからいっしょにべんきょうしよう。",
        translation: { pt: "Olá. Sou a Aiko. A partir de hoje vamos estudar juntos.", en: "Hello. I'm Aiko. From today, let's study together." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "よろしくお願いします、先生。",
            politeKana: "よろしくおねがいします、せんせい。",
            casual: "よろしくね、先生！",
            casualKana: "よろしくね、せんせい！",
            translation: { pt: "Conto com a senhora, professora.", en: "I'm in your care, teacher." },
          },
          {
            polite: "少しきんちょうしています…",
            politeKana: "すこしきんちょうしています…",
            casual: "ちょっときんちょうする…",
            casualKana: "ちょっときんちょうする…",
            translation: { pt: "Tô um pouco nervoso(a)…", en: "I'm a little nervous…" },
          },
        ],
      },
      {
        speaker: "aiko",
        polite: "大丈夫ですよ。日本語には、ていねいな話し方と、カジュアルな話し方があります。",
        politeKana: "だいじょうぶですよ。にほんごには、ていねいなはなしかたと、カジュアルなはなしかたがあります。",
        casual: "大丈夫。日本語にはね、ていねいな話し方とカジュアルな話し方があるの。",
        casualKana: "だいじょうぶ。にほんごにはね、ていねいなはなしかたとカジュアルなはなしかたがあるの。",
        translation: { pt: "Tranquilo. O japonês tem um jeito polido de falar e um jeito casual.", en: "It's okay. Japanese has a polite way of speaking and a casual way." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "両方、勉強したいです。",
            politeKana: "りょうほう、べんきょうしたいです。",
            casual: "両方、勉強したい！",
            casualKana: "りょうほう、べんきょうしたい！",
            translation: { pt: "Quero aprender os dois.", en: "I want to learn both." },
          },
          {
            polite: "むずかしそうですね…",
            politeKana: "むずかしそうですね…",
            casual: "むずかしそう…",
            casualKana: "むずかしそう…",
            translation: { pt: "Parece difícil…", en: "That sounds hard…" },
          },
        ],
      },
      {
        speaker: "aiko",
        polite: "いい心がけです。少しずつ、両方できるようになりますよ。次は、あなたの番ですね。",
        politeKana: "いいこころがけです。すこしずつ、りょうほうできるようになりますよ。つぎは、あなたのばんですね。",
        casual: "いい心がけ。少しずつ、両方できるようになるよ。次は、あなたの番ね。",
        casualKana: "いいこころがけ。すこしずつ、りょうほうできるようになるよ。つぎは、あなたのばんね。",
        translation: { pt: "Boa atitude. Aos poucos você domina os dois. Da próxima vez, é a sua vez de falar. ✨", en: "Good attitude. Little by little you'll manage both. Next time, it'll be your turn to speak. ✨" },
      },
    ],
  },
  {
    id: "w2-aiko-register",
    week: 2,
    medium: "irl",
    title: { pt: "Aiko: polido ou casual?", en: "Aiko: polite or casual?" },
    scene: {
      pt: "Aiko desenha uma balança no quadro: de um lado です・ます, do outro タメ口.",
      en: "Aiko draws a scale on the board: です・ます on one side, タメ口 on the other.",
    },
    register: "neutral",
    characterId: "aiko",
    lines: [
      {
        speaker: "aiko",
        polite: "質問です。友だちに『ありがとう』と『ありがとうございます』、どちらを使いますか？",
        politeKana: "しつもんです。ともだちに『ありがとう』と『ありがとうございます』、どちらをつかいますか？",
        casual: "質問ね。友だちには『ありがとう』と『ありがとうございます』、どっちを使う？",
        casualKana: "しつもんね。ともだちには『ありがとう』と『ありがとうございます』、どっちをつかう？",
        translation: { pt: "Pergunta: com um amigo, você usa 'arigatou' ou 'arigatou gozaimasu'?", en: "A question: with a friend, do you use 'arigatou' or 'arigatou gozaimasu'?" },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "友だちには『ありがとう』です。",
            politeKana: "ともだちには『ありがとう』です。",
            casual: "友だちには『ありがとう』！",
            casualKana: "ともだちには『ありがとう』！",
            translation: { pt: "Com amigo é 'arigatou'.", en: "With a friend, it's 'arigatou'." },
          },
          {
            polite: "うーん、わかりません…",
            politeKana: "うーん、わかりません…",
            casual: "うーん、わかんない…",
            casualKana: "うーん、わかんない…",
            translation: { pt: "Hmm, não sei…", en: "Hmm, I'm not sure…" },
          },
        ],
      },
      {
        speaker: "aiko",
        polite: "その通りです！友だちにはカジュアル、先生や店員さんにはていねいに、ですね。",
        politeKana: "そのとおりです！ともだちにはカジュアル、せんせいやてんいんさんにはていねいに、ですね。",
        casual: "その通り！友だちにはカジュアル、先生や店員さんにはていねいに、ね。",
        casualKana: "そのとおり！ともだちにはカジュアル、せんせいやてんいんさんにはていねいに、ね。",
        translation: { pt: "Exato! Casual com amigos, polido com professores e atendentes.", en: "Exactly! Casual with friends, polite with teachers and shop staff." },
      },
      {
        speaker: "you",
        polite: "",
        casual: "",
        translation: { pt: "", en: "" },
        choices: [
          {
            polite: "だんだん、わかってきました。",
            politeKana: "だんだん、わかってきました。",
            casual: "だんだん、わかってきた！",
            casualKana: "だんだん、わかってきた！",
            translation: { pt: "Aos poucos tô pegando.", en: "I'm starting to get it." },
          },
          {
            polite: "もっと練習したいです。",
            politeKana: "もっとれんしゅうしたいです。",
            casual: "もっと練習したい！",
            casualKana: "もっとれんしゅうしたい！",
            translation: { pt: "Quero praticar mais.", en: "I want to practice more." },
          },
        ],
      },
      {
        speaker: "aiko",
        polite: "その調子です。次の会話で、ためしてみましょう。楽しみにしていますね。",
        politeKana: "そのちょうしです。つぎのかいわで、ためしてみましょう。たのしみにしていますね。",
        casual: "その調子。次の会話で、ためしてみよう。楽しみにしてるね。",
        casualKana: "そのちょうし。つぎのかいわで、ためしてみよう。たのしみにしてるね。",
        translation: { pt: "É isso aí. Na próxima conversa, experimenta. Vou estar torcendo. 🌸", en: "That's the spirit. Try it in your next conversation. I'll be rooting for you. 🌸" },
      },
    ],
  },
];

/** Ordem canônica dos personagens no elenco de conversas. */
export const CHAR_ORDER = ["yuki", "crush", "kenji", "hana", "aiko"];
