import type { KanaItem } from "../types";

/**
 * Semana 2: os 46 katakana básicos. Katakana é usado para palavras
 * estrangeiras (コーヒー, スマホ), então os mnemônicos puxam por palavras
 * emprestadas que o aluno já reconhece.
 */
export const KATAKANA: KanaItem[] = [
  { id: "a", kana: "ア", romaji: "a", row: "ア", mnemonic: { pt: "'a' de アメリカ (América). Um 'A' com o topo cortado.", en: "'a' as in アメリカ (America). An 'A' with its top cut off." } },
  { id: "i", kana: "イ", romaji: "i", row: "ア", mnemonic: { pt: "'i'. Duas linhas, como um 'i' inclinado — parece uma pessoa andando.", en: "'i'. Two strokes, like a leaning person walking." } },
  { id: "u", kana: "ウ", romaji: "u", row: "ア", mnemonic: { pt: "'u'. Um chapéu com antena — o 'u' de ウーロン茶 (chá oolong).", en: "'u'. A hat with an antenna — the 'u' of ウーロン (oolong)." } },
  { id: "e", kana: "エ", romaji: "e", row: "ア", mnemonic: { pt: "'ê' (fechado). Parece um 'E' de engenharia (エンジニア).", en: "'e' as in 'bed'. Looks like a capital 'E' rotated." } },
  { id: "o", kana: "オ", romaji: "o", row: "ア", mnemonic: { pt: "'ô' (fechado). Um sinal de mais com uma perna — オレンジ (laranja).", en: "'o' as in 'go'. A plus sign with a leg — オレンジ (orange)." } },
  { id: "ka", kana: "カ", romaji: "ka", row: "カ", mnemonic: { pt: "'ka' de カメラ (câmera). Quase igual ao hiragana か sem o traço.", en: "'ka' as in カメラ (camera). Almost the hiragana か without the dash." } },
  { id: "ki", kana: "キ", romaji: "ki", row: "カ", mnemonic: { pt: "'ki'. Parece uma chave (key) — ligado ao hiragana き.", en: "'ki'. Looks like a key — related to hiragana き." } },
  { id: "ku", kana: "ク", romaji: "ku", row: "カ", mnemonic: { pt: "'ku' de クリスマス. Um bico aberto de pássaro.", en: "'ku' as in クリスマス (Christmas). An open bird beak." } },
  { id: "ke", kana: "ケ", romaji: "ke", row: "カ", mnemonic: { pt: "'kê'. Parece um 'K' magrinho — ケーキ (cake/bolo).", en: "'ke' as in ケーキ (cake). A skinny 'K'." } },
  { id: "ko", kana: "コ", romaji: "ko", row: "カ", mnemonic: { pt: "'kô'. Dois traços em canto — コーヒー (café).", en: "'ko' as in コーヒー (coffee). Two strokes forming a corner." } },
  { id: "sa", kana: "サ", romaji: "sa", row: "サ", mnemonic: { pt: "'sa' de サラダ (salada). Parece o hiragana さ mais reto.", en: "'sa' as in サラダ (salad). Like a straighter hiragana さ." } },
  { id: "shi", kana: "シ", romaji: "shi", row: "サ", mnemonic: { pt: "'shi'. Dois pontinhos e um traço subindo — cuidado: parece ツ! (シ sobe)", en: "'shi'. Two dots and an upward stroke — careful, looks like ツ! (シ sweeps up)" } },
  { id: "su", kana: "ス", romaji: "su", row: "サ", mnemonic: { pt: "'su' de スープ (sopa) / スマホ. Um gancho descendo.", en: "'su' as in スープ (soup). A hook coming down." } },
  { id: "se", kana: "セ", romaji: "se", row: "サ", mnemonic: { pt: "'sê'. Parece o hiragana せ endurecido.", en: "'se'. Like a stiffened hiragana せ." } },
  { id: "so", kana: "ソ", romaji: "so", row: "サ", mnemonic: { pt: "'sô'. Um ponto e um traço descendo — cuidado: parece ン! (ソ desce reto)", en: "'so'. A dot and a downward stroke — careful, looks like ン! (ソ drops straight)" } },
  { id: "ta", kana: "タ", romaji: "ta", row: "タ", mnemonic: { pt: "'ta'. Parece um キ diferente — de タクシー (táxi).", en: "'ta' as in タクシー (taxi)." } },
  { id: "chi", kana: "チ", romaji: "chi", row: "タ", mnemonic: { pt: "'tchi'. Parece um '+' com telhado — チーズ (queijo/cheese).", en: "'chi' as in チーズ (cheese). A '+' with a roof." } },
  { id: "tsu", kana: "ツ", romaji: "tsu", row: "タ", mnemonic: { pt: "'tsu'. Dois pontos e um traço — parece シ, mas ツ desce reto.", en: "'tsu'. Two dots — looks like シ, but ツ sweeps down straight." } },
  { id: "te", kana: "テ", romaji: "te", row: "タ", mnemonic: { pt: "'tê'. Como o hiragana て com telhado — テスト (teste).", en: "'te' as in テスト (test). Like hiragana て with a roof." } },
  { id: "to", kana: "ト", romaji: "to", row: "タ", mnemonic: { pt: "'tô'. Um 'T' minúsculo — トマト (tomate).", en: "'to' as in トマト (tomato). A little 't'." } },
  { id: "na", kana: "ナ", romaji: "na", row: "ナ", mnemonic: { pt: "'na'. Um '+' inclinado — ナイフ (faca/knife).", en: "'na' as in ナイフ (knife). A tilted '+'." } },
  { id: "ni", kana: "ニ", romaji: "ni", row: "ナ", mnemonic: { pt: "'ni'. Duas linhas = 2 (ni!) — como um sinal de igual.", en: "'ni'. Two lines = 2 (ni!). Like an equals sign." } },
  { id: "nu", kana: "ヌ", romaji: "nu", row: "ナ", mnemonic: { pt: "'nu'. Um X com cauda — parece o ク com traço a mais.", en: "'nu'. An X with a tail — like ク plus a stroke." } },
  { id: "ne", kana: "ネ", romaji: "ne", row: "ナ", mnemonic: { pt: "'nê'. Um traço e um nó — parece ホ apertado.", en: "'ne'. A cross with a knot." } },
  { id: "no", kana: "ノ", romaji: "no", row: "ナ", mnemonic: { pt: "'nô'. Um traço só descendo pra esquerda. O katakana mais simples!", en: "'no'. A single stroke down-left. The simplest katakana!" } },
  { id: "ha", kana: "ハ", romaji: "ha", row: "ハ", mnemonic: { pt: "'ha'. Dois traços abrindo — como um telhadinho.", en: "'ha'. Two strokes opening like a little roof." } },
  { id: "hi", kana: "ヒ", romaji: "hi", row: "ハ", mnemonic: { pt: "'hi'. Parece um 'L' com um traço — de ヒーロー (herói).", en: "'hi' as in ヒーロー (hero). Like an 'L' with a stroke." } },
  { id: "fu", kana: "フ", romaji: "fu", row: "ハ", mnemonic: { pt: "'fu'. Um gancho simples — フォーク (garfo/fork).", en: "'fu' as in フォーク (fork). A simple hook." } },
  { id: "he", kana: "ヘ", romaji: "he", row: "ハ", mnemonic: { pt: "'hê'. IDÊNTICO ao hiragana へ! Montanha baixinha.", en: "'he'. IDENTICAL to hiragana へ! A low mountain." } },
  { id: "ho", kana: "ホ", romaji: "ho", row: "ハ", mnemonic: { pt: "'hô'. Um '+' com duas pernas — parece 木 (árvore).", en: "'ho'. A '+' with two legs — looks like 木 (tree)." } },
  { id: "ma", kana: "マ", romaji: "ma", row: "マ", mnemonic: { pt: "'ma'. Um triângulo com rabo — マスク (máscara).", en: "'ma' as in マスク (mask). A triangle with a tail." } },
  { id: "mi", kana: "ミ", romaji: "mi", row: "マ", mnemonic: { pt: "'mi'. Três traços = três (parece o número 3 deitado).", en: "'mi'. Three strokes (like a sideways 3)." } },
  { id: "mu", kana: "ム", romaji: "mu", row: "マ", mnemonic: { pt: "'mu'. Um pequeno canto com ponto — de ゲーム (game/jogo).", en: "'mu' as in ゲーム (game). A small corner with a dot." } },
  { id: "me", kana: "メ", romaji: "me", row: "マ", mnemonic: { pt: "'mê'. Um 'X' — parece o hiragana め sem laço. メール (e-mail).", en: "'me' as in メール (email). An 'X'." } },
  { id: "mo", kana: "モ", romaji: "mo", row: "マ", mnemonic: { pt: "'mô'. Parece o hiragana も mais reto.", en: "'mo'. Like a straighter hiragana も." } },
  { id: "ya", kana: "ヤ", romaji: "ya", row: "ヤ", mnemonic: { pt: "'ia'. Um gancho com traço — parece o hiragana や simplificado.", en: "'ya'. A hook with a stroke — a simplified や." } },
  { id: "yu", kana: "ユ", romaji: "yu", row: "ヤ", mnemonic: { pt: "'iu'. Um 'U' quadrado deitado — ユーロ (euro).", en: "'yu' as in ユーロ (euro). A squared, lying 'U'." } },
  { id: "yo", kana: "ヨ", romaji: "yo", row: "ヤ", mnemonic: { pt: "'iô'. Parece um 'E' de costas / um 3 quadrado.", en: "'yo'. Like a backwards 'E' / a squared 3." } },
  { id: "ra", kana: "ラ", romaji: "ra", row: "ラ", mnemonic: { pt: "'ra'. Um traço e um gancho — ラーメン (ramen)!", en: "'ra' as in ラーメン (ramen). A stroke and a hook." } },
  { id: "ri", kana: "リ", romaji: "ri", row: "ラ", mnemonic: { pt: "'ri'. Dois traços verticais — parece o hiragana り.", en: "'ri'. Two vertical strokes — like hiragana り." } },
  { id: "ru", kana: "ル", romaji: "ru", row: "ラ", mnemonic: { pt: "'ru'. Duas perninhas curvando — de ビール (cerveja/beer).", en: "'ru' as in ビール (beer). Two curving legs." } },
  { id: "re", kana: "レ", romaji: "re", row: "ラ", mnemonic: { pt: "'rê'. Um único traço em 'L' invertido — レストラン (restaurante).", en: "'re' as in レストラン (restaurant). A single check-mark stroke." } },
  { id: "ro", kana: "ロ", romaji: "ro", row: "ラ", mnemonic: { pt: "'rô'. Um quadrado perfeito — a 'boca' 口.", en: "'ro'. A perfect square — the 'mouth' 口." } },
  { id: "wa", kana: "ワ", romaji: "wa", row: "ワ", mnemonic: { pt: "'ua'. Parece フ com uma perna — cuidado com ラ e ウ!", en: "'wa'. Like フ with a leg — careful vs ラ and ウ!" } },
  { id: "wo", kana: "ヲ", romaji: "wo (o)", row: "ワ", mnemonic: { pt: "'ô'. Raríssimo em katakana. Parece ラ com traço a mais.", en: "'o'. Very rare in katakana. Like ラ with an extra stroke." } },
  { id: "n", kana: "ン", romaji: "n", row: "ワ", mnemonic: { pt: "'n' nasal. Um ponto e um traço subindo — parece ソ, mas ン sobe!", en: "nasal 'n'. A dot and an upward sweep — looks like ソ, but ン goes up!" } },
];
